#!/bin/bash
echo compiling with max optimizations...
g++ test.cpp Hmm.cpp Matrix.cpp ColumnMatrix.cpp DiscreteHmmDataset.cpp Flyweight.cpp --std=c++11 -O2 -o testHmm
#g++ test.cpp Hmm.cpp DiscreteHmmDataset.cpp --std=c++11 -o testHmm
